### ISSUE TITLE
(FE) Develop Home Page View

### ISSUE THREAD

**Issue by mpasricha1** [mpasricha1/style_me#10]
Create a homepage for the application, should allow the user to log in or sign up and provide some detail about what the site does

**Comment by mpasricha1** [comment]
The two buttons need to redirect to the following routes 

signup-btn -> /signup 
login-btn -> /login

**Comment by enyasantiago** [comment]
login btn redirects to login
sign up btn redirects to addnew

**Comment by mpasricha1** [comment]
Tested buttons, everything is working. Closing issue
