### ISSUE TITLE
(FE) Develop User Sign Up View

### ISSUE THREAD

**Issue by mpasricha1** [mpasricha1/style_me#14]
Design a view for the user to sign up. 
Required fields: 
first name 
last name
email 
password 

Optional fields: 
age 
gender 
(Anything else that anyone things should be captured)

**Comment by mpasricha1** [comment]
Cancel button should be a link back to the home page.

**Comment by jenniferjael** [comment]
cancel btn done

**Comment by mpasricha1** [comment]
Tested and working. Closing issue.
