### ISSUE TITLE
(FE) Develop Add New Item View

### ISSUE THREAD

**Issue by mpasricha1** [mpasricha1/style_me#23]
Develop the view that allows the user to add a new item. This should be where they can upload a image or take an image and add the details for the new item. Then submit it to be added to the database

**Comment by mpasricha1** [comment]
Can you convert the categories input to a drop down. I updated the backend to send an object to the page that contains an id and the category name.  You can use the object to create the drop down list using handlebars. Add the id tag to the tag and can you send that back in the form submit instead of the category name. 

I added a categories-seed.sql file in the db folder for some test data. So just do a pull before hand. 

Should probably put a placeholder picture in the image spot for when there is no image.

**Comment by Esmendez90** [comment]
wrote the code to send back the category id instead of the category_name. Unable to test yet as im still unable to run the server. currently working on it...

**Comment by Esmendez90** [comment]
this is done. All category names render in the dropdown list in handlebars  file.

**Comment by Esmendez90** [comment]
Added a placeholder image also. 
Im sending back category id, item_name, image url, and thumbnail url. However, the route doesn't seem to work. I get an error when i send back the data.

**Comment by mpasricha1** [comment]
Everything testing and working.

closing
