### ISSUE TITLE
Develop Cloudinary Javascript

### ISSUE THREAD

**Issue by mpasricha1** [mpasricha1/style_me#24]
Develop the javascript to send the cloudniary url back to the server 

route not defined yet.

**Comment by mpasricha1** [comment]
Going to add both of you to this because you both worked on it. In the cloudinary api, can you move your keys to the .env file. They shouldn't be public on the page.

**Comment by Esmendez90** [comment]
sorry, i'm exactly clear on this. you mean sending the website url back to server? so `cloudinary.com`?

**Comment by mpasricha1** [comment]
![image](https://user-images.githubusercontent.com/61244786/112777113-5337b100-900f-11eb-9174-4381931b63a8.png)

cloudname and uploadpreset should be moved to the .env file and loaded from there.

**Comment by mpasricha1** [comment]
This doesn't seem to work. closing for now
