### ISSUE TITLE
(FE) Develop User Login View

### ISSUE THREAD

**Issue by mpasricha1** [mpasricha1/style_me#3]
Design the log in page for users to log in 

Required fields: 
email 
password

**Comment by mpasricha1** [comment]
All html code must be in a handlebars file.

**Comment by Esmendez90** [comment]
Changed the html to a handlebars file. Working on the js file now using Anthony's example as template.

**Comment by mpasricha1** [comment]
Tested files, both javascript and handlebars file working. closing issue.
