### ISSUE TITLE
Folder Restructure for CSS and JS files

### ISSUE THREAD

**Issue by mpasricha1** [mpasricha1/style_me#4]
CSS and JS files should be in the public folder. I do not believe the folder was copied over when I merged my code with main so will need to be created. 

app/public/css 
app/public/js

@Esmendez90  I assigned this to you because it looks like you will need to rewrite your script and css path in login file.

**Comment by Esmendez90** [comment]
Yes, I created a public folder and moved the css and js folder inside of it. Rewrote the paths as well.

**Comment by mpasricha1** [comment]
closing issue.
