### ISSUE TITLE
Add wrong username/password message on login screen

### ISSUE THREAD

**Issue by mpasricha1** [mpasricha1/style_me#7]
Looks like this code didn't make it back into the the login screen. Need to add code back in to this file to indicate if users email or password is wrong.

**Comment by Esmendez90** [comment]
Done. Should be ok now.

**Comment by mpasricha1** [comment]
Its not quite working properly, but I think that is because of my code. If you put a space in the password field and submit it then the message pops up. But if you submit with the wrong password I am not seeing an error.

**Comment by Esmendez90** [comment]
George was helping me with this and looks like the code is doing what it's supposed to, however, since we don't have an actual email with password in our database then there is nothing to validate the email/ psw against. More to come...

**Comment by mpasricha1** [comment]
Used a custom callback in the post route to login to get this to work. Closing issue
